# Generated by Django 4.2.5 on 2023-09-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_todolist_duedate_alter_todolist_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
