# Generated by Django 4.2.5 on 2023-09-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_todolist_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='dueDate',
            field=models.DateTimeField(null=True),
        ),
    ]
