# Generated by Django 4.2.5 on 2023-10-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_todolist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user_id',
            new_name='userId',
        ),
    ]
