# Generated by Django 3.2.7 on 2023-10-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
