# Generated by Django 3.2.7 on 2023-10-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_timestamp_message_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
